
# ###################
# # STAGE 2: runner
# ###################

FROM openjdk:8-jre-alpine as runner

WORKDIR /app

ENV FC_LANG en-US LC_CTYPE en_US.UTF-8
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# dependencies
RUN echo "https://mirrors.aliyun.com/alpine/v3.6/main/" >/etc/apk/repositories && echo "https://mirrors.aliyun.com/alpine/v3.6/community/" >>/etc/apk/repositories
RUN apk -U upgrade && apk add --no-cache bash ttf-dejavu fontconfig

# # add fixed cacerts
# COPY --from=builder /etc/ssl/certs/java/cacerts /opt/java/openjdk/lib/security/cacerts

# add Metabase script and uberjar
RUN mkdir -p bin target/uberjar
COPY target/uberjar/metabase.jar /app/target/uberjar/
COPY bin/start /app/bin/

# create the plugins directory, with writable permissions
RUN mkdir -p /plugins && chmod a+rwx /plugins

# expose our default runtime port
EXPOSE 3000

# run it
ENTRYPOINT ["/app/bin/start"]
